### PR TITLE
Consolidate setup method

### PR DESCRIPTION
**Pull request by MaHaWo**
ok, so this PR creates tons of changes because until now the setup method was part of the tests and played the role of a fixture, while now it is part of the code and is something that must be tested in itself. As such, the tests should not depend on it in the complete way they did before, and a mock install should be created instead. 
Second, the path structure the setup creates should not be interfered with by the tests, hence a lot of path references had to be changed. 

- add setup routine as a part of `src/iSparrow` by copying over the one that until now lived in the tests. 
  - creates folders for output, models, examples, cached files and config files 
  - makes sure the shipped model files are downloaded and put into the `models` folder 
  - does not create data folder anymore, as this is the responsibility of the recorder system. merely takes it as a config now for watcher. 
- do not use actual setup routine in tests - this is handled by fixtures 
  - this change introduces a fixture hierarchy which is build such that a new install is created for almost each test case, to isolate test cases as much as possible.  Redownloading stuff is avoided now.
- use env variable for indicating whether sparrow runs in test mode. Necessary for caching in `SpeciesPredictor`. Should probably be changed later.  
- remove some code in `utils.py` that was never used and will not be in the foreseeable future 
- add `update_dict_leafs_recursive` method for updating the leafs of nested dicts based on a template. Used for updating configs 
- add default config files for install and run 
- add tests for methods in `utils.py`
- add tests for `set_up_sparrow`. 
- remove the model code files from the repo. they live [here](https://huggingface.co/MaHaWo/iSparrow_test_models/tree/main) now, together with the actual model files. 
- remove the `copy_files` method from the setup module 
- put the config files into the src/iSparrow directory such that it becomes accessible to `importlib.resources`. Removes `__file__` based path lookup upon install 
- add `MANIFEST.in` for the default config files, since we will be  using setuptools for building most probably. 
- cause `SpeciesPredictorBase` to use the correct cache directory during tests or production.
- use `platformdirs` instead of deprecated `appdirs`
- add options for tensorflow install: tflite-runtime is used on ARM (raspberry...), and is only available on linux, while tensorflow itself can be run everywhere, but is gigantic. Therefore, tensorflow is not installed by default and you need to choose which one you want explicitly. tflite_runtime can speed up loading times quite a lot, but cannot work with .pb files.
- removed a bunch of dependencies we don´t need anymore.

### CODE REVIEW

**Comment by MaHaWo** [comment]
sorry, not yet ready. had to change around a few things with path lookup.

**Review by iulusoy — DISMISSED** [review]

**Comment by iulusoy** [comment]
Though it seems to me it is re-downloading files for each test - let me check.

**Comment by MaHaWo** [comment]
ok, this should be better now, without redownloading file every time and without using the setup method to create a test environment in the tests. There's lots of removals this time, mainly because of the model/preprocessor implementation being removed now into their respective huggingface repos. The many file changes came about because when moving the install/setup methods into src from tests and having a more independent test setup, the tests had to be adjusted. sorry it became so big and messy ...

**Review by iulusoy — COMMENTED** [review]
Looks better now, but it still seems to be downloading the example files for each test?

**Comment by MaHaWo** [comment]
pooch caches them and only copies them over, at least that's what should happen. I could make the download thing a fixture with session scope so it happens only once, but since tests create a new environment on purpose so that they are independent, the copying over will probably remain.

**Review by iulusoy — APPROVED** [review]

**Comment by MaHaWo** [comment]
I changed the fixtures in such a way that copying/downloading happens only once, and added a readme element that describes the setup method.

**Pull request merged**
