### PR TITLE
16 integrate model class into analyzer

### PR DESCRIPTION
**Pull request by MaHaWo**
# Summary: 
## Functionality changes and additions
- remove `Analyzer` class: It's functionality is now provided by `Model` and `Preprocessor`. 
- reflect this in changed name in config: `Analyzer` --> `Analysis`.
- adjust existing tests where necessary
- add `name` attribute to the `model` class to allow for testing that the right module is loaded analogously to `preprocessor`. 

## Refactoring and maintenance
(could, maybe should, have been done in separate PR, but it seems a little too much effort for such a simpe thing) 

- remove `read_audio_data` method from preprocessor implementations and move to base class - it's always the same. Leave to `process_data` method in derived classes though for birdnet stuff, to illustrate usage idea. 
- put attributes of preprocessors into base class because they are all the same.
- left the test fixtures alone for now.

### CODE REVIEW

**Comment by MaHaWo** [comment]
Hello @iulusoy, this one is ready I think, if you have time to give it a look. 
I added a summary at the top to help with guidance. Lots of files changed, but most of them are small. Only really big change is the removal of the analyzer and the refactoring of the preprocessor.

**Review by iulusoy — APPROVED** [review]
Looks great! Can we include a demo jupyter notebook where you provide a custom recording (for example, the test one for now) and run the models? It would make it easier to show to them what you did. I think you mentioned using some notebooks for test purposes?

**Comment by iulusoy** [comment]
Also, I like the higher layer of abstraction with moving things from the specific preprocessors to the base class, same for the models.

**Comment by iulusoy** [comment]
> Maybe merge this first and add the example notebooks separately? or should I do it here right away? @iulusoy

Yes, this should be merged first and the demo should be a separate PR.

**Pull request merged**
